# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-26 19:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userName', models.CharField(max_length=150)),
                ('userEmail', models.CharField(max_length=150)),
                ('userPassword', models.CharField(max_length=150)),
                ('userImage', models.TextField(blank=True, max_length=150)),
            ],
        ),
    ]
