# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-27 17:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='userImage',
            field=models.TextField(blank=True, max_length=5000),
        ),
    ]
