# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-09 23:33
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0002_auto_20171027_1733'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='userEmail',
        ),
        migrations.RemoveField(
            model_name='users',
        name='userName',
        ),
        migrations.RemoveField(
            model_name='users',
            name='userPassword',
        ),
        migrations.AddField(
            model_name='users',
            name='user',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
     ]
