# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-06 22:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20171027_1733'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='userEmail',
            field=models.CharField(max_length=150, unique=True),
        ),
    ]
