# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-27 17:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20171114_1718'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='userToken',
            field=models.TextField(blank=True, max_length=5000),
        ),
    ]
