# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-20 19:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
        ('propositions', '0004_auto_20171007_0228'),
    ]

    operations = [
        migrations.CreateModel(
            name='Answers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ansewrType', models.IntegerField()),
                ('propositions', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='propositionFK', to='propositions.Propositions')),
                ('users', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='userFK', to='users.Users')),
            ],
        ),
    ]
