# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-30 22:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('propositions', '0005_propositions_propositionlink'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='propositions',
            name='questionnaire',
        ),
    ]
