language: python
python:
  - "3.4"

env:
  - DJANGO_VERSION=1.11.6

# command to install dependencies

install:
  - pip install -q Django==$DJANGO_VERSION
  - pip install -r requirements.txt
  - pip install coveralls
  
# command to run tests
script:
  - coverage run --source=2017.2-DEPUTINDER-API setup.py test
  
after_success:
  - coveralls

deploy:
  provider: heroku
  api_key: 9568926c-7b1d-4623-9fab-bd921061470b
  on: development
  run:
    - "python manage.py flush"
    - "python manage.py makemigrations"
    - "python manage.py migrate"
    - "python manage.py parserAllData"