language: python
python:
- '3.4'
env:
- DJANGO_VERSION=1.11.6
install:
- pip install -q Django==$DJANGO_VERSION
- pip install -r requirements.txt
- pip install coveralls
script:
- coverage run --source=DepuTinder_API manage.py test
- coverage run --source=question manage.py test
- coverage run --source=propositions manage.py test
- coverage run --source=parlamentarians manage.py test
- coverage run --source=candidateRanking manage.py test
- coverage run --source=questionnaire manage.py test
- coverage run --source=votings manage.py test
- coverage run --source=users manage.py test
after_success:
- coveralls
deploy:
  provider: heroku
  api_key: 68991c0a-7c6e-4b3f-9bbb-9f962c6fe783
  run: "python manage.py migrate"
  app: deputinder-api
  on:
    repo: fga-gpp-mds/2017.2-DepuTinder-API
