# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-13 02:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidateRanking', '0002_auto_20171213_0139'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidateranking',
            name='ranking',
            field=models.CharField(max_length=999999),
        ),
    ]
