# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-07 01:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Questionnaire',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('questionnaireID', models.PositiveIntegerField()),
            ],
        ),
    ]
