# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-31 01:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaire', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionnaire',
            name='questionsTotal',
            field=models.PositiveIntegerField(default=10),
        ),
    ]
