# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-31 01:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaire', '0002_questionnaire_questionstotal'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questionnaire',
            name='id',
        ),
        migrations.AlterField(
            model_name='questionnaire',
            name='questionnaireID',
            field=models.PositiveIntegerField(primary_key=True, serialize=False),
        ),
    ]
