# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-24 12:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0004_remove_question_questionnaire'),
        ('questionnaire', '0004_auto_20171123_1718'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questionnaire',
            name='questionsTotal',
        ),
        migrations.AddField(
            model_name='questionnaire',
            name='questions',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question', to='question.Question'),
        ),
    ]
