# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-24 13:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaire', '0006_auto_20171124_1311'),
    ]

    operations = [
        migrations.RenameField(
            model_name='questionnaire',
            old_name='questions',
            new_name='questionsFK',
        ),
    ]
