# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-24 15:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaire', '0007_auto_20171124_1321'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questionnaire',
            name='questionsFK',
        ),
        migrations.AddField(
            model_name='questionnaire',
            name='maxQuestions',
            field=models.IntegerField(default=10),
        ),
        migrations.AddField(
            model_name='questionnaire',
            name='totalQuestions',
            field=models.IntegerField(),
        ),
    ]
