# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-12 22:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaire', '0008_auto_20171124_1534'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionnaire',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
