# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-13 00:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaire', '0009_auto_20171212_2218'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionnaire',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
