# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-30 23:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('propositions', '0005_propositions_propositionlink'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('questionTitle', models.CharField(blank=True, max_length=100)),
                ('questionSubtitle', models.CharField(blank=True, max_length=150)),
                ('questionDescription', models.CharField(blank=True, max_length=200)),
                ('questionAuthor', models.CharField(blank=True, max_length=50)),
                ('questionLink', models.CharField(blank=True, max_length=50)),
                ('proposition', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='proposition', to='propositions.Propositions')),
            ],
        ),
    ]
