# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-21 22:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0003_remove_question_questionlink'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='questionnaire',
        ),
    ]
