# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-24 15:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaire', '0008_auto_20171124_1534'),
        ('question', '0004_remove_question_questionnaire'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='questionnaire',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='questionnaire', to='questionnaire.Questionnaire'),
        ),
    ]
