# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-11 19:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Parlamentarians',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('candidadeName', models.CharField(max_length=150)),
                ('candidadeUF', models.CharField(max_length=3)),
                ('candidadePoliticalParty', models.IntegerField()),
            ],
        ),
    ]
