# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-11 20:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parlamentarians', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='parlamentarians',
            old_name='candidadeName',
            new_name='nome',
        ),
        migrations.RenameField(
            model_name='parlamentarians',
            old_name='candidadePoliticalParty',
            new_name='partido',
        ),
        migrations.RenameField(
            model_name='parlamentarians',
            old_name='candidadeUF',
            new_name='uf',
        ),
    ]
