# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-13 00:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parlamentarians', '0004_auto_20171017_2310'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parlamentarians',
            name='parlamentaryUF',
            field=models.CharField(max_length=6),
        ),
    ]
