# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-02 23:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('votings', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='votings',
            old_name='CandidateId',
            new_name='candidateId',
        ),
        migrations.RenameField(
            model_name='votings',
            old_name='CandidateVote',
            new_name='candidateVote',
        ),
    ]
