# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-27 18:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('votings', '0004_auto_20171027_1835'),
    ]

    operations = [
        migrations.AlterField(
            model_name='votings',
            name='propositionID',
            field=models.ForeignKey(default=0, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='propositionID', to='propositions.Propositions'),
        ),
    ]
