# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-31 00:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('votings', '0005_auto_20171027_1836'),
    ]

    operations = [
        migrations.AlterField(
            model_name='votings',
            name='propositionID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='votings_id', to='propositions.Propositions'),
        ),
    ]
